### ISSUE TITLE
Postprocess of objects after parsing

### ISSUE THREAD

**Issue by RafaelVidaurre** [Finciero/gurkha#2]
Since `Gurkha` usually returns arrays of objects built from a schema, I propose the following directive:

`$post`, this directive would run a post-process on the created object, this is quite useful for doing things to objects **after** their properties have been successfully parsed

``` javascript
var transactionSchema = {
  description: '.desc',
  ...
  $post: function (transaction) {
    return new Transaciton(transaction).build();
  }
};
```

**Comment by monitz87** [comment]
Done!
